from pathlib import Path
from typing import Iterable

import torch
from PIL import Image
from transformers import (
    AutoProcessor,
    Qwen2_5_VLForConditionalGeneration,
)
from qwen_vl_utils import process_vision_info


class QwenModel:
    """
    Interface to Qwen2.5-VL for visual anomaly reasoning.

    This module is responsible only for:
    1. Loading the Qwen vision-language model.
    2. Preparing visual frames and a reasoning prompt.
    3. Running Qwen inference.
    4. Returning Qwen's raw textual response.

    It does NOT:
    - perform object detection,
    - perform tracking,
    - classify scenes,
    - build surveillance context,
    - generate the dynamic prompt,
    - decide anomaly status itself outside Qwen's reasoning.
    """

    DEFAULT_MODEL_NAME = "Qwen/Qwen2.5-VL-3B-Instruct"

    def __init__(
        self,
        model_name: str = DEFAULT_MODEL_NAME,
        max_new_tokens: int = 128,
    ):
        """
        Initialize the Qwen model.

        Parameters
        ----------
        model_name : str
            Hugging Face model identifier or local model path.

        max_new_tokens : int
            Maximum number of tokens generated by Qwen.
        """

        self.model_name = model_name
        self.max_new_tokens = max_new_tokens

        # ---------------------------------------------------------
        # Device selection
        # ---------------------------------------------------------

        self.device = torch.device(
            "cuda" if torch.cuda.is_available() else "cpu"
        )

        print("=" * 70)
        print("Loading Qwen...")
        print(f"Model : {self.model_name}")
        print(f"Device: {self.device}")
        print("=" * 70)

        # ---------------------------------------------------------
        # Processor
        # ---------------------------------------------------------

# Don't preserve unnecessarily high visual resolution. Compress each image into a manageable number of visual tokens before reasoning.
# We're deliberately starting conservatively because we're working with a 15 GB Tesla T4.


        self.processor = AutoProcessor.from_pretrained(
        self.model_name,
        trust_remote_code=True,
        min_pixels=256 * 28 * 28,
        max_pixels=512 * 28 * 28,
)

        # ---------------------------------------------------------
        # Model
        # ---------------------------------------------------------

        dtype = (
            torch.float16
            if torch.cuda.is_available()
            else torch.float32
        )

        self.model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            self.model_name,
            trust_remote_code=True,
            torch_dtype=dtype,
            device_map="auto",
        )

        self.model.eval()

        print("Qwen loaded successfully.")

    # -------------------------------------------------------------
    # Image loading
    # -------------------------------------------------------------

    def _load_image(self, frame):
        """
        Convert a frame input into a PIL RGB image.

        Parameters
        ----------
        frame : Path, str, or PIL.Image.Image

        Returns
        -------
        PIL.Image.Image
        """

        if isinstance(frame, Image.Image):
            return frame.convert("RGB")

        if isinstance(frame, (str, Path)):
            return Image.open(frame).convert("RGB")

        raise TypeError(
            "Frame must be a PIL image, string path, or Path object."
        )

    # -------------------------------------------------------------
    # Message construction
    # -------------------------------------------------------------

    def _build_message(
        self,
        frames: Iterable,
        prompt: str,
    ):
        """
        Build a Qwen multimodal message.

        All supplied frames are included as visual evidence,
        followed by the dynamic reasoning prompt.
        """

        content = []

        for frame in frames:

            image = self._load_image(frame)

            content.append(
                {
                    "type": "image",
                    "image": image,
                }
            )

        content.append(
            {
                "type": "text",
                "text": prompt,
            }
        )

        message = [
            {
                "role": "system",
                "content": (
                    "You are a visual surveillance anomaly "
                    "reasoning system. Analyze the provided "
                    "visual evidence together with the supplied "
                    "context and follow the user's reasoning "
                    "instructions exactly."
                ),
            },
            {
                "role": "user",
                "content": content,
            },
        ]

        return message

    # -------------------------------------------------------------
    # Inference
    # -------------------------------------------------------------

    def generate(
        self,
        frames: Iterable,
        prompt: str,
    ) -> str:
        """
        Run Qwen reasoning on a set of frames.

        Parameters
        ----------
        frames : iterable
            Sequence of image paths or PIL images.

        prompt : str
            Dynamic prompt generated by DynamicPromptGenerator.

        Returns
        -------
        str
            Raw textual response generated by Qwen.
        """

        frames = list(frames)

        if not frames:
            raise ValueError(
                "At least one frame must be supplied to Qwen."
            )

        if not prompt or not prompt.strip():
            raise ValueError(
                "Qwen prompt cannot be empty."
            )

        message = self._build_message(
            frames=frames,
            prompt=prompt,
        )

        # ---------------------------------------------------------
        # Convert message to Qwen processor format
        # ---------------------------------------------------------

        text = self.processor.apply_chat_template(
            message,
            tokenize=False,
            add_generation_prompt=True,
        )

        image_inputs, video_inputs = process_vision_info(
            message
        )

        inputs = self.processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        )

        # ---------------------------------------------------------
        # Move tensors to the model device
        # ---------------------------------------------------------

        inputs = inputs.to(self.device)

        # ---------------------------------------------------------
        # Generate response
        # ---------------------------------------------------------

        with torch.inference_mode():

            generated_ids = self.model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=False,
            )

        # ---------------------------------------------------------
        # Remove input tokens from generated sequence
        # ---------------------------------------------------------

        generated_ids_trimmed = [
            output_ids[len(input_ids):]
            for input_ids, output_ids in zip(
                inputs.input_ids,
                generated_ids,
            )
        ]

        # ---------------------------------------------------------
        # Decode Qwen response
        # ---------------------------------------------------------

        output_text = self.processor.batch_decode(
            generated_ids_trimmed,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        )[0]

        return output_text.strip()